-- =============================================================================
-- RLS — module lot-alerts
-- DDL aligné projet Supabase live kpjflntnotftpzffjbud (2026-09-03)
-- Rôles canoniques app : admin | équipe (member = legacy CHECK seulement)
-- =============================================================================
-- is_pharma_staff() ALL. migrations/006
